# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'gateway-service'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8600']

  - job_name: 'user-service'
    scrape_interval: 15s
    metrics_path: '/user-service/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8600']

  - job_name: 'database-service'
    scrape_interval: 15s
    metrics_path: '/database-service/actuator/prometheus'
    static_configs:
      - targets: [ 'database-service:8600' ]

  - job_name: 'apporder-service'
    scrape_interval: 15s
    metrics_path: '/apporder-service/actuator/prometheus'
    static_configs:
      - targets: [ 'apporder-service:8600' ]

  - job_name: 'storage-service'
    scrape_interval: 15s
    metrics_path: '/storage-service/actuator/prometheus'
    static_configs:
      - targets: [ 'storage-service:8600' ]

  - job_name: 'container-service'
    scrape_interval: 15s
    metrics_path: '/container-service/actuator/prometheus'
    static_configs:
      - targets: [ 'container-service:8600' ]

  - job_name: 'zipkin'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['zipkin:9411']
    metric_relabel_configs:
      # Response code count
      - source_labels: [__name__]
        regex: '^status_(\d+)_(.*)$'
        replacement: '${1}'
        target_label: status
      - source_labels: [__name__]
        regex: '^status_(\d+)_(.*)$'
        replacement: '${2}'
        target_label: path
      - source_labels: [__name__]
        regex: '^status_(\d+)_(.*)$'
        replacement: 'http_requests_total'
        target_label: __name__
      # Response time, pending histogram from https://github.com/openzipkin/zipkin/pull/1609
      - source_labels: [__name__]
        regex: '^response_(.*)$'
        replacement: '${1}'
        target_label: path
      - source_labels: [__name__]
        regex: '^response_(.*)$'
        replacement: 'http_request_duration_milliseconds'
        target_label: __name__